/**
 * v0.18.7 Sprint 2.7 — Token-savings estimator for the dashboard.
 *
 * Computes ESTIMATED tokens saved per project over a time window by
 * comparing actual SC-tool consumption against documented counterfactuals
 * for what the equivalent native flow would have cost.
 *
 * THIS IS A DIRECTIONAL METRIC, NOT A PRECISE MEASUREMENT. The
 * counterfactual is unknowable; we use industry-typical baselines from
 * CLAUDE.md's documented analysis. Operators should treat this as
 * "ballpark of value generated by SC" rather than "exact savings."
 *
 * Sources for the assumed baselines:
 *   - CLAUDE.md "Token Comparison by Operation" table
 *   - Sprint 0/1 benchmark notes
 *
 * If your real workflow systematically differs from these baselines,
 * tune the constants by setting:
 *   ZC_SAVINGS_RECALL_BASELINE   (default 30000)
 *   ZC_SAVINGS_SEARCH_BASELINE   (default 25000)
 *   ZC_SAVINGS_SUMMARY_BASELINE  (default 5000)
 *   ZC_SAVINGS_FETCH_BASELINE    (default 8000)
 */

import { withClient } from "../pg_pool.js";

/**
 * Counterfactual baselines: tokens-per-call you would have spent in the
 * equivalent native flow if SC didn't exist. Conservative-leaning numbers
 * pulled from CLAUDE.md. Tunable via env.
 */
function envInt(name: string, dflt: number): number {
  const raw = process.env[name];
  if (!raw) return dflt;
  const n = parseInt(raw, 10);
  return Number.isFinite(n) && n >= 0 ? n : dflt;
}

const BASELINE = {
  recall_context: () => envInt("ZC_SAVINGS_RECALL_BASELINE", 30_000),  // re-paste 5-20 files at session start
  search:         () => envInt("ZC_SAVINGS_SEARCH_BASELINE", 25_000),  // read 5-10 files to find a pattern
  file_summary:   () => envInt("ZC_SAVINGS_SUMMARY_BASELINE", 5_000),  // read whole file when only purpose was needed
  check:          () => envInt("ZC_SAVINGS_CHECK_BASELINE",   8_000),  // read multiple files to verify a fact
  fetch:          () => envInt("ZC_SAVINGS_FETCH_BASELINE",   8_000),  // paste full webpage into context
};

/**
 * Tools that REPLACE a native flow (the "savings producers"). Each maps to
 * its baseline category. Other tools (zc_remember, zc_summarize_session,
 * zc_broadcast, etc.) are SC-internal mechanics — they don't produce savings,
 * so they're excluded from the calculation.
 */
const SAVING_TOOL_MAP: Record<string, keyof typeof BASELINE> = {
  zc_recall_context: "recall_context",
  zc_search:         "search",
  zc_search_global:  "search",
  zc_file_summary:   "file_summary",
  zc_check:          "check",
  zc_fetch:          "fetch",
  zc_batch:          "search",  // batch is search-shaped
};

export interface ToolUsageRow {
  tool_name:      string;
  call_count:     number;
  input_tokens:   number;  // sum of input_tokens across calls
  output_tokens:  number;  // sum of output_tokens
  cost_usd:       number;  // sum of cost_usd
}

export interface PerToolSavings {
  tool_name:           string;
  call_count:          number;
  actual_tokens:       number;       // input + output, summed across calls
  actual_cost_usd:     number;
  baseline_per_call:   number;       // counterfactual tokens per call
  estimated_native_tokens: number;   // baseline × call_count
  saved_tokens:        number;       // estimated_native - actual (clamped >= 0)
  saved_cost_usd:      number;       // saved_tokens × avg cost-per-token
}

export interface SavingsSummary {
  project_hash:           string;
  since:                  string;          // ISO timestamp
  until:                  string;          // ISO timestamp
  per_tool:               PerToolSavings[];
  total_actual_tokens:    number;
  total_actual_cost_usd:  number;
  total_estimated_native_tokens: number;
  total_saved_tokens:     number;
  total_saved_cost_usd:   number;
  reduction_pct:          number;          // 0..100
  /** "high" / "medium" / "low" — heuristic on call count + tool diversity */
  confidence:             "low" | "medium" | "high";
  caveats:                string[];
}

/**
 * Average cost-per-token. Sonnet 4.6 input ~$3/MTok, output ~$15/MTok.
 * For "saved cost" we use the avg input price as the baseline (savings
 * are mostly input-side: avoided context-pasting). Tunable.
 */
function avgCostPerToken(): number {
  return parseFloat(process.env.ZC_SAVINGS_AVG_COST_PER_TOKEN ?? "0.000003");  // $3/MTok input default
}

/**
 * Pull aggregated tool-usage rows from tool_calls_pg for a project window.
 *
 * v0.22.2 — also returns per-call honest_native_tokens via SQL CASE expression.
 * Previously the snapshotter applied a flat baseline (e.g. 30,000 tokens for
 * every zc_recall_context call) which over-credited cache-hit/sparse recalls
 * and could under-credit content-rich ones. The new model uses the actual
 * output_tokens of each call multiplied by an amplification factor that
 * varies by tool + content size. Discovered live: 7/19 zc_recall_context
 * calls in A2A_communication returned only 326 tokens (sparse-content recalls)
 * but were credited as 30,000 each — overstating savings by ~210k tokens.
 *
 * AMPLIFICATION FACTORS (per call) — what fraction of "what native Claude
 * would have read to derive the same knowledge" each token represents:
 *   zc_recall_context: 1.2× when output<1k (sparse), 4.0× when ≥1k (real)
 *   zc_search:         3.0× (search results condense ~3 source files each)
 *   zc_search_global:  3.0×
 *   zc_file_summary:   25× (200-tok summary represents 5,000-tok file)
 *   zc_check:          5.0× (memory-first answer represents pages of context)
 *   zc_fetch:          1.5× (fetched content is essentially the source itself)
 *   zc_batch:          3.0× (search-like)
 * Tunable per-tool via env vars ZC_SAVINGS_AMPLIFICATION_<TOOL>.
 */
export async function fetchToolUsage(
  projectHash: string,
  sinceIso: string,
  untilIso: string,
): Promise<ToolUsageRow[]> {
  return withClient(async (c) => {
    const envF = (k: string, dflt: number): number => {
      const v = parseFloat(process.env[k] ?? "");
      return Number.isFinite(v) && v > 0 ? v : dflt;
    };
    const amp = {
      recall_sparse:  envF("ZC_SAVINGS_AMP_RECALL_SPARSE",  1.2),
      recall_full:    envF("ZC_SAVINGS_AMP_RECALL_FULL",    4.0),
      search:         envF("ZC_SAVINGS_AMP_SEARCH",         3.0),
      file_summary:   envF("ZC_SAVINGS_AMP_FILE_SUMMARY",   25.0),
      check:          envF("ZC_SAVINGS_AMP_CHECK",          5.0),
      fetch:          envF("ZC_SAVINGS_AMP_FETCH",          1.5),
    };
    const sparseThreshold = parseInt(process.env.ZC_SAVINGS_RECALL_SPARSE_THRESHOLD ?? "1000", 10);

    const res = await c.query<{
      tool_name: string;
      call_count: string;
      input_tokens: string;
      output_tokens: string;
      cost_usd: string;
      honest_native_tokens: string;
    }>(
      `SELECT tool_name,
              COUNT(*)::text         AS call_count,
              COALESCE(SUM(input_tokens),  0)::text AS input_tokens,
              COALESCE(SUM(output_tokens), 0)::text AS output_tokens,
              COALESCE(SUM(cost_usd),      0)::text AS cost_usd,
              COALESCE(SUM(
                CASE
                  WHEN tool_name = 'zc_recall_context' AND output_tokens < $4
                    THEN output_tokens * $5
                  WHEN tool_name = 'zc_recall_context'
                    THEN output_tokens * $6
                  WHEN tool_name IN ('zc_search', 'zc_search_global', 'zc_batch')
                    THEN output_tokens * $7
                  WHEN tool_name = 'zc_file_summary'
                    THEN output_tokens * $8
                  WHEN tool_name = 'zc_check'
                    THEN output_tokens * $9
                  WHEN tool_name = 'zc_fetch'
                    THEN output_tokens * $10
                  ELSE 0
                END
              ), 0)::text AS honest_native_tokens
         FROM tool_calls_pg
        WHERE project_hash = $1
          AND ts >= $2::timestamptz
          AND ts <  $3::timestamptz
        GROUP BY tool_name
        ORDER BY tool_name`,
      [
        projectHash, sinceIso, untilIso,
        sparseThreshold, amp.recall_sparse, amp.recall_full,
        amp.search, amp.file_summary, amp.check, amp.fetch,
      ],
    );
    return res.rows.map((r) => ({
      tool_name:             r.tool_name,
      call_count:            parseInt(r.call_count, 10),
      input_tokens:          parseInt(r.input_tokens, 10),
      output_tokens:         parseInt(r.output_tokens, 10),
      cost_usd:              parseFloat(r.cost_usd),
      // v0.22.2 — per-call honest native equivalent (sum of CASE expression)
      honest_native_tokens:  parseInt(r.honest_native_tokens, 10),
    }));
  });
}

/**
 * Compute the savings summary for a project + time window.
 *
 * Sums per-tool actuals from tool_calls_pg, applies counterfactual
 * baselines for SC retrieval tools, returns a structured breakdown.
 */
export async function computeSavings(
  projectHash: string,
  sinceIso: string,
  untilIso: string,
): Promise<SavingsSummary> {
  const usage   = await fetchToolUsage(projectHash, sinceIso, untilIso);
  const cost_per_token = avgCostPerToken();

  let total_actual_tokens = 0;
  let total_actual_cost   = 0;
  let total_native        = 0;
  const per_tool: PerToolSavings[] = [];

  for (const row of usage) {
    const actual_tokens = row.input_tokens + row.output_tokens;
    total_actual_tokens += actual_tokens;
    total_actual_cost   += row.cost_usd;

    const baselineKey = SAVING_TOOL_MAP[row.tool_name];
    if (!baselineKey) continue;  // tool doesn't produce savings (just internal mechanics)

    const baseline_per_call = BASELINE[baselineKey]();
    const estimated_native  = baseline_per_call * row.call_count;
    const saved_tokens      = Math.max(0, estimated_native - actual_tokens);
    const saved_cost_usd    = saved_tokens * cost_per_token;
    total_native           += estimated_native;

    per_tool.push({
      tool_name:               row.tool_name,
      call_count:              row.call_count,
      actual_tokens,
      actual_cost_usd:         row.cost_usd,
      baseline_per_call,
      estimated_native_tokens: estimated_native,
      saved_tokens,
      saved_cost_usd,
    });
  }

  const total_saved = Math.max(0, total_native - total_actual_tokens);
  const reduction   = total_native > 0 ? (total_saved / total_native) * 100 : 0;

  // Confidence heuristic: more calls + more tool diversity → higher confidence
  const totalCalls = per_tool.reduce((a, t) => a + t.call_count, 0);
  const distinctTools = per_tool.length;
  let confidence: SavingsSummary["confidence"] = "low";
  if (totalCalls >= 50 && distinctTools >= 3)      confidence = "high";
  else if (totalCalls >= 15 && distinctTools >= 2) confidence = "medium";

  const caveats: string[] = [
    "Savings are ESTIMATED — counterfactual is unknowable. Baselines are from CLAUDE.md documented analysis.",
    `Baseline assumptions: zc_recall_context=${BASELINE.recall_context()}t, zc_search=${BASELINE.search()}t, zc_file_summary=${BASELINE.file_summary()}t, zc_fetch=${BASELINE.fetch()}t per call.`,
    `Cost saved uses avg $${avgCostPerToken().toFixed(8)}/token (override via ZC_SAVINGS_AVG_COST_PER_TOKEN).`,
    "Excluded from savings: zc_remember, zc_summarize_session, zc_broadcast, zc_record_*, zc_*_task — these are SC-internal mechanics, not retrieval replacements.",
  ];
  if (totalCalls < 15) caveats.push("⚠ Low confidence: fewer than 15 SC tool calls in this window — numbers will be very rough.");

  return {
    project_hash: projectHash,
    since:        sinceIso,
    until:        untilIso,
    per_tool:     per_tool.sort((a, b) => b.saved_tokens - a.saved_tokens),
    total_actual_tokens,
    total_actual_cost_usd:  total_actual_cost,
    total_estimated_native_tokens: total_native,
    total_saved_tokens:     total_saved,
    total_saved_cost_usd:   total_saved * cost_per_token,
    reduction_pct:          Math.round(reduction * 10) / 10,
    confidence,
    caveats,
  };
}

/**
 * Render the savings summary as an HTML fragment for the dashboard panel.
 */
export function renderSavingsHtml(summary: SavingsSummary, projectName: string | null): string {
  const fmt = (n: number) => n.toLocaleString("en-US");
  const fmtCost = (n: number) => "$" + n.toFixed(4);
  const projectLabel = projectName
    ? `<span class="project-name">${projectName}</span>`
    : `<span class="project-name unresolved">project:${summary.project_hash.slice(0, 8)}…</span>`;
  const confidenceColor = { low: "#f87171", medium: "#fbbf24", high: "#4ade80" }[summary.confidence];

  if (summary.total_actual_tokens === 0 && summary.total_estimated_native_tokens === 0) {
    return `<p class="empty">No SC tool activity recorded in this window for project ${projectLabel}.</p>`;
  }

  const rows = summary.per_tool.length === 0
    ? `<tr><td colspan="5" class="empty">No retrieval-tool calls in window. SC was used only for non-retrieval mechanics (broadcasts, queue, etc.).</td></tr>`
    : summary.per_tool.map((t) => `
      <tr>
        <td><code>${t.tool_name}</code></td>
        <td>${fmt(t.call_count)}</td>
        <td>${fmt(t.actual_tokens)}</td>
        <td>${fmt(t.estimated_native_tokens)}</td>
        <td class="savings-cell"><strong>${fmt(t.saved_tokens)}</strong> (${fmtCost(t.saved_cost_usd)})</td>
      </tr>
    `).join("");

  return `
    <div class="savings-summary">
      <div class="savings-header">
        Project: ${projectLabel}<br>
        Window: ${summary.since.slice(0, 10)} → ${summary.until.slice(0, 10)}<br>
        Confidence: <span style="color:${confidenceColor}">${summary.confidence}</span>
      </div>
      <div class="savings-totals">
        <div class="savings-tile">
          <div class="savings-tile-num">${fmt(summary.total_saved_tokens)}</div>
          <div class="savings-tile-label">tokens saved (estimated)</div>
        </div>
        <div class="savings-tile">
          <div class="savings-tile-num">${fmtCost(summary.total_saved_cost_usd)}</div>
          <div class="savings-tile-label">cost saved (USD)</div>
        </div>
        <div class="savings-tile">
          <div class="savings-tile-num">${summary.reduction_pct.toFixed(1)}%</div>
          <div class="savings-tile-label">reduction vs native</div>
        </div>
        <div class="savings-tile">
          <div class="savings-tile-num">${fmt(summary.total_actual_tokens)}</div>
          <div class="savings-tile-label">actual SC tokens</div>
        </div>
      </div>
      <table class="savings-table">
        <thead>
          <tr>
            <th>SC tool</th>
            <th>Calls</th>
            <th>Actual tokens</th>
            <th>Native equivalent</th>
            <th>Saved</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
      <details class="savings-methodology">
        <summary>How this is computed (caveats + assumptions)</summary>
        <ul>
          ${summary.caveats.map((c) => `<li>${c}</li>`).join("")}
        </ul>
      </details>
    </div>
  `;
}
