// Auto-generated by scripts/sync-roles-from-dispatcher.mjs
// Source: A2A_dispatcher/roles.json (103 roles)
// Generated: 2026-05-06T03:11:15.498Z
//
// DO NOT EDIT BY HAND. Re-run the sync script when the dispatcher's role
// list changes:
//   node scripts/sync-roles-from-dispatcher.mjs

export interface RoleEntry {
  name: string;
  desc: string;
}

export const ROLES_CATALOG: RoleEntry[] = [
  {
    "name": "developer",
    "desc": "code implementation, testing, debugging, and technical architecture"
  },
  {
    "name": "marketer",
    "desc": "marketing strategy, content creation, brand messaging, copywriting, and go-to-market planning"
  },
  {
    "name": "researcher",
    "desc": "market research, competitive analysis, user research, data gathering, and strategic insights"
  },
  {
    "name": "designer",
    "desc": "UI/UX design, wireframes, visual design systems, and frontend styling"
  },
  {
    "name": "writer",
    "desc": "documentation, technical writing, README files, API docs, and user guides"
  },
  {
    "name": "analyst",
    "desc": "data analysis, metrics, reporting, and quantitative research"
  },
  {
    "name": "devops",
    "desc": "CI/CD pipelines, deployment, infrastructure, Docker, and monitoring"
  },
  {
    "name": "security",
    "desc": "security engineering -- threat modeling, vulnerability analysis, secure code review, exploit-aware hardening, and defense-in-depth architecture"
  },
  {
    "name": "strategist",
    "desc": "business strategy -- idea validation, unit economics, competitive positioning, pivot decisions, and cross-project learning synthesis"
  },
  {
    "name": "growth",
    "desc": "growth engineering -- funnels, onboarding optimization, retention, pricing experiments, A/B testing, AARRR metrics, and revenue optimization"
  },
  {
    "name": "mutator",
    "desc": "DEPRECATED legacy alias — same as mutator-general (Sprint 2.7 mutator pool fallback). Use mutator-<pool> for domain-specific mutators."
  },
  {
    "name": "qa",
    "desc": "quality assurance -- E2E testing from user perspective, regression testing, accessibility auditing, edge case discovery, and user acceptance testing"
  },
  {
    "name": "mutator_pools",
    "desc": ""
  },
  {
    "name": "mutator-engineering",
    "desc": "Code, tests, infrastructure, security. Skills produce or critique technical artifacts. (Sprint 2.7 mutator pool)"
  },
  {
    "name": "mutator-product",
    "desc": "Requirements, prioritization, user stories, roadmaps, decision documents. (Sprint 2.7 mutator pool)"
  },
  {
    "name": "mutator-design",
    "desc": "User experience, visual design, design systems, design research. (Sprint 2.7 mutator pool)"
  },
  {
    "name": "mutator-marketing",
    "desc": "Demand generation, channel optimization, audience targeting, campaign design. (Sprint 2.7 mutator pool)"
  },
  {
    "name": "mutator-sales",
    "desc": "Pipeline mechanics, deal management, customer conversations, competitive positioning. (Sprint 2.7 mutator pool)"
  },
  {
    "name": "mutator-content",
    "desc": "Long-form and short-form written content production. (Sprint 2.7 mutator pool)"
  },
  {
    "name": "mutator-brand",
    "desc": "Brand voice, positioning, narrative architecture, identity systems. (Sprint 2.7 mutator pool)"
  },
  {
    "name": "mutator-research",
    "desc": "Discovery, synthesis, evidence-based conclusions, research methodology. (Sprint 2.7 mutator pool)"
  },
  {
    "name": "mutator-legal",
    "desc": "Contracts, compliance, risk assessment, regulatory frameworks, policy review. (Sprint 2.7 mutator pool)"
  },
  {
    "name": "mutator-finance",
    "desc": "Financial modeling, accounting, treasury, FP&A, board reporting. (Sprint 2.7 mutator pool)"
  },
  {
    "name": "mutator-hr",
    "desc": "People processes, hiring, development, compensation design, culture. (Sprint 2.7 mutator pool)"
  },
  {
    "name": "mutator-operations",
    "desc": "Process design, project execution, cross-functional coordination, throughput optimization. (Sprint 2.7 mutator pool)"
  },
  {
    "name": "mutator-customer",
    "desc": "Customer-facing communication, support workflows, retention, expansion. (Sprint 2.7 mutator pool)"
  },
  {
    "name": "mutator-strategy",
    "desc": "Strategic planning, board materials, executive briefings, M&A diligence. (Sprint 2.7 mutator pool)"
  },
  {
    "name": "mutator-general",
    "desc": "Fallback for skills without explicit intended_roles. Conservative, body-style-preserving mutations. (Sprint 2.7 mutator pool)"
  },
  {
    "name": "architect",
    "desc": "Code, tests, infrastructure, security. Skills produce or critique technical artifacts. (Sprint 2.7 worker role; mutator pool: mutator-engineering)"
  },
  {
    "name": "sre",
    "desc": "Code, tests, infrastructure, security. Skills produce or critique technical artifacts. (Sprint 2.7 worker role; mutator pool: mutator-engineering)"
  },
  {
    "name": "data-engineer",
    "desc": "Code, tests, infrastructure, security. Skills produce or critique technical artifacts. (Sprint 2.7 worker role; mutator pool: mutator-engineering)"
  },
  {
    "name": "ml-engineer",
    "desc": "Code, tests, infrastructure, security. Skills produce or critique technical artifacts. (Sprint 2.7 worker role; mutator pool: mutator-engineering)"
  },
  {
    "name": "platform-engineer",
    "desc": "Code, tests, infrastructure, security. Skills produce or critique technical artifacts. (Sprint 2.7 worker role; mutator pool: mutator-engineering)"
  },
  {
    "name": "product-manager",
    "desc": "Requirements, prioritization, user stories, roadmaps, decision documents. (Sprint 2.7 worker role; mutator pool: mutator-product)"
  },
  {
    "name": "product-owner",
    "desc": "Requirements, prioritization, user stories, roadmaps, decision documents. (Sprint 2.7 worker role; mutator pool: mutator-product)"
  },
  {
    "name": "business-analyst",
    "desc": "Requirements, prioritization, user stories, roadmaps, decision documents. (Sprint 2.7 worker role; mutator pool: mutator-product)"
  },
  {
    "name": "product-designer",
    "desc": "User experience, visual design, design systems, design research. (Sprint 2.7 worker role; mutator pool: mutator-design)"
  },
  {
    "name": "ux-researcher",
    "desc": "User experience, visual design, design systems, design research. (Sprint 2.7 worker role; mutator pool: mutator-design)"
  },
  {
    "name": "ui-designer",
    "desc": "User experience, visual design, design systems, design research. (Sprint 2.7 worker role; mutator pool: mutator-design)"
  },
  {
    "name": "graphic-designer",
    "desc": "User experience, visual design, design systems, design research. (Sprint 2.7 worker role; mutator pool: mutator-design)"
  },
  {
    "name": "brand-designer",
    "desc": "User experience, visual design, design systems, design research. (Sprint 2.7 worker role; mutator pool: mutator-design)"
  },
  {
    "name": "interaction-designer",
    "desc": "User experience, visual design, design systems, design research. (Sprint 2.7 worker role; mutator pool: mutator-design)"
  },
  {
    "name": "growth-marketer",
    "desc": "Demand generation, channel optimization, audience targeting, campaign design. (Sprint 2.7 worker role; mutator pool: mutator-marketing)"
  },
  {
    "name": "content-marketer",
    "desc": "Demand generation, channel optimization, audience targeting, campaign design. (Sprint 2.7 worker role; mutator pool: mutator-marketing)"
  },
  {
    "name": "seo-specialist",
    "desc": "Demand generation, channel optimization, audience targeting, campaign design. (Sprint 2.7 worker role; mutator pool: mutator-marketing)"
  },
  {
    "name": "social-media-manager",
    "desc": "Demand generation, channel optimization, audience targeting, campaign design. (Sprint 2.7 worker role; mutator pool: mutator-marketing)"
  },
  {
    "name": "performance-marketer",
    "desc": "Demand generation, channel optimization, audience targeting, campaign design. (Sprint 2.7 worker role; mutator pool: mutator-marketing)"
  },
  {
    "name": "demand-gen",
    "desc": "Demand generation, channel optimization, audience targeting, campaign design. (Sprint 2.7 worker role; mutator pool: mutator-marketing)"
  },
  {
    "name": "lifecycle-marketer",
    "desc": "Demand generation, channel optimization, audience targeting, campaign design. (Sprint 2.7 worker role; mutator pool: mutator-marketing)"
  },
  {
    "name": "sales-rep",
    "desc": "Pipeline mechanics, deal management, customer conversations, competitive positioning. (Sprint 2.7 worker role; mutator pool: mutator-sales)"
  },
  {
    "name": "account-executive",
    "desc": "Pipeline mechanics, deal management, customer conversations, competitive positioning. (Sprint 2.7 worker role; mutator pool: mutator-sales)"
  },
  {
    "name": "sdr",
    "desc": "Pipeline mechanics, deal management, customer conversations, competitive positioning. (Sprint 2.7 worker role; mutator pool: mutator-sales)"
  },
  {
    "name": "sales-engineer",
    "desc": "Pipeline mechanics, deal management, customer conversations, competitive positioning. (Sprint 2.7 worker role; mutator pool: mutator-sales)"
  },
  {
    "name": "partnerships",
    "desc": "Pipeline mechanics, deal management, customer conversations, competitive positioning. (Sprint 2.7 worker role; mutator pool: mutator-sales)"
  },
  {
    "name": "channel-manager",
    "desc": "Pipeline mechanics, deal management, customer conversations, competitive positioning. (Sprint 2.7 worker role; mutator pool: mutator-sales)"
  },
  {
    "name": "copywriter",
    "desc": "Long-form and short-form written content production. (Sprint 2.7 worker role; mutator pool: mutator-content)"
  },
  {
    "name": "content-writer",
    "desc": "Long-form and short-form written content production. (Sprint 2.7 worker role; mutator pool: mutator-content)"
  },
  {
    "name": "editor",
    "desc": "Long-form and short-form written content production. (Sprint 2.7 worker role; mutator pool: mutator-content)"
  },
  {
    "name": "blogger",
    "desc": "Long-form and short-form written content production. (Sprint 2.7 worker role; mutator pool: mutator-content)"
  },
  {
    "name": "technical-writer",
    "desc": "Long-form and short-form written content production. (Sprint 2.7 worker role; mutator pool: mutator-content)"
  },
  {
    "name": "documentation-writer",
    "desc": "Long-form and short-form written content production. (Sprint 2.7 worker role; mutator pool: mutator-content)"
  },
  {
    "name": "brand-strategist",
    "desc": "Brand voice, positioning, narrative architecture, identity systems. (Sprint 2.7 worker role; mutator pool: mutator-brand)"
  },
  {
    "name": "brand-manager",
    "desc": "Brand voice, positioning, narrative architecture, identity systems. (Sprint 2.7 worker role; mutator pool: mutator-brand)"
  },
  {
    "name": "creative-director",
    "desc": "Brand voice, positioning, narrative architecture, identity systems. (Sprint 2.7 worker role; mutator pool: mutator-brand)"
  },
  {
    "name": "brand-architect",
    "desc": "Brand voice, positioning, narrative architecture, identity systems. (Sprint 2.7 worker role; mutator pool: mutator-brand)"
  },
  {
    "name": "market-analyst",
    "desc": "Discovery, synthesis, evidence-based conclusions, research methodology. (Sprint 2.7 worker role; mutator pool: mutator-research)"
  },
  {
    "name": "competitive-intel",
    "desc": "Discovery, synthesis, evidence-based conclusions, research methodology. (Sprint 2.7 worker role; mutator pool: mutator-research)"
  },
  {
    "name": "user-researcher",
    "desc": "Discovery, synthesis, evidence-based conclusions, research methodology. (Sprint 2.7 worker role; mutator pool: mutator-research)"
  },
  {
    "name": "data-analyst",
    "desc": "Discovery, synthesis, evidence-based conclusions, research methodology. (Sprint 2.7 worker role; mutator pool: mutator-research)"
  },
  {
    "name": "research-scientist",
    "desc": "Discovery, synthesis, evidence-based conclusions, research methodology. (Sprint 2.7 worker role; mutator pool: mutator-research)"
  },
  {
    "name": "legal-counsel",
    "desc": "Contracts, compliance, risk assessment, regulatory frameworks, policy review. (Sprint 2.7 worker role; mutator pool: mutator-legal)"
  },
  {
    "name": "compliance-officer",
    "desc": "Contracts, compliance, risk assessment, regulatory frameworks, policy review. (Sprint 2.7 worker role; mutator pool: mutator-legal)"
  },
  {
    "name": "contracts-reviewer",
    "desc": "Contracts, compliance, risk assessment, regulatory frameworks, policy review. (Sprint 2.7 worker role; mutator pool: mutator-legal)"
  },
  {
    "name": "privacy-officer",
    "desc": "Contracts, compliance, risk assessment, regulatory frameworks, policy review. (Sprint 2.7 worker role; mutator pool: mutator-legal)"
  },
  {
    "name": "regulatory-affairs",
    "desc": "Contracts, compliance, risk assessment, regulatory frameworks, policy review. (Sprint 2.7 worker role; mutator pool: mutator-legal)"
  },
  {
    "name": "accountant",
    "desc": "Financial modeling, accounting, treasury, FP&A, board reporting. (Sprint 2.7 worker role; mutator pool: mutator-finance)"
  },
  {
    "name": "financial-analyst",
    "desc": "Financial modeling, accounting, treasury, FP&A, board reporting. (Sprint 2.7 worker role; mutator pool: mutator-finance)"
  },
  {
    "name": "treasurer",
    "desc": "Financial modeling, accounting, treasury, FP&A, board reporting. (Sprint 2.7 worker role; mutator pool: mutator-finance)"
  },
  {
    "name": "fpa",
    "desc": "Financial modeling, accounting, treasury, FP&A, board reporting. (Sprint 2.7 worker role; mutator pool: mutator-finance)"
  },
  {
    "name": "controller",
    "desc": "Financial modeling, accounting, treasury, FP&A, board reporting. (Sprint 2.7 worker role; mutator pool: mutator-finance)"
  },
  {
    "name": "finance-manager",
    "desc": "Financial modeling, accounting, treasury, FP&A, board reporting. (Sprint 2.7 worker role; mutator pool: mutator-finance)"
  },
  {
    "name": "recruiter",
    "desc": "People processes, hiring, development, compensation design, culture. (Sprint 2.7 worker role; mutator pool: mutator-hr)"
  },
  {
    "name": "hr-generalist",
    "desc": "People processes, hiring, development, compensation design, culture. (Sprint 2.7 worker role; mutator pool: mutator-hr)"
  },
  {
    "name": "ld-specialist",
    "desc": "People processes, hiring, development, compensation design, culture. (Sprint 2.7 worker role; mutator pool: mutator-hr)"
  },
  {
    "name": "comp-analyst",
    "desc": "People processes, hiring, development, compensation design, culture. (Sprint 2.7 worker role; mutator pool: mutator-hr)"
  },
  {
    "name": "people-ops",
    "desc": "People processes, hiring, development, compensation design, culture. (Sprint 2.7 worker role; mutator pool: mutator-hr)"
  },
  {
    "name": "talent-partner",
    "desc": "People processes, hiring, development, compensation design, culture. (Sprint 2.7 worker role; mutator pool: mutator-hr)"
  },
  {
    "name": "diversity-officer",
    "desc": "People processes, hiring, development, compensation design, culture. (Sprint 2.7 worker role; mutator pool: mutator-hr)"
  },
  {
    "name": "ops-manager",
    "desc": "Process design, project execution, cross-functional coordination, throughput optimization. (Sprint 2.7 worker role; mutator pool: mutator-operations)"
  },
  {
    "name": "project-manager",
    "desc": "Process design, project execution, cross-functional coordination, throughput optimization. (Sprint 2.7 worker role; mutator pool: mutator-operations)"
  },
  {
    "name": "scrum-master",
    "desc": "Process design, project execution, cross-functional coordination, throughput optimization. (Sprint 2.7 worker role; mutator pool: mutator-operations)"
  },
  {
    "name": "program-manager",
    "desc": "Process design, project execution, cross-functional coordination, throughput optimization. (Sprint 2.7 worker role; mutator pool: mutator-operations)"
  },
  {
    "name": "supply-chain-manager",
    "desc": "Process design, project execution, cross-functional coordination, throughput optimization. (Sprint 2.7 worker role; mutator pool: mutator-operations)"
  },
  {
    "name": "process-engineer",
    "desc": "Process design, project execution, cross-functional coordination, throughput optimization. (Sprint 2.7 worker role; mutator pool: mutator-operations)"
  },
  {
    "name": "support-agent",
    "desc": "Customer-facing communication, support workflows, retention, expansion. (Sprint 2.7 worker role; mutator pool: mutator-customer)"
  },
  {
    "name": "customer-success-manager",
    "desc": "Customer-facing communication, support workflows, retention, expansion. (Sprint 2.7 worker role; mutator pool: mutator-customer)"
  },
  {
    "name": "technical-support",
    "desc": "Customer-facing communication, support workflows, retention, expansion. (Sprint 2.7 worker role; mutator pool: mutator-customer)"
  },
  {
    "name": "account-manager",
    "desc": "Customer-facing communication, support workflows, retention, expansion. (Sprint 2.7 worker role; mutator pool: mutator-customer)"
  },
  {
    "name": "implementation-specialist",
    "desc": "Customer-facing communication, support workflows, retention, expansion. (Sprint 2.7 worker role; mutator pool: mutator-customer)"
  },
  {
    "name": "chief-of-staff",
    "desc": "Strategic planning, board materials, executive briefings, M&A diligence. (Sprint 2.7 worker role; mutator pool: mutator-strategy)"
  },
  {
    "name": "consultant",
    "desc": "Strategic planning, board materials, executive briefings, M&A diligence. (Sprint 2.7 worker role; mutator pool: mutator-strategy)"
  },
  {
    "name": "board-advisor",
    "desc": "Strategic planning, board materials, executive briefings, M&A diligence. (Sprint 2.7 worker role; mutator pool: mutator-strategy)"
  },
  {
    "name": "head-of-strategy",
    "desc": "Strategic planning, board materials, executive briefings, M&A diligence. (Sprint 2.7 worker role; mutator pool: mutator-strategy)"
  }
];

export const ROLE_NAMES: Set<string> = new Set(ROLES_CATALOG.map((r) => r.name));
